replicaCount: 2

image:
  repository: nitzanm594/weatherapp-tsg
  tag: "54" 
  pullPolicy: Always
imagePullSecrets:
  - name: dockerhub
service:
  type: NodePort
  port:  9090
  targetPort: 9090
  nodePort: 30000

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: my-python-app.local
      paths:
        - path: /
          pathType: ImplementationSpecific


resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autScaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80


config:
  bgColor: "blue"  # Default blue, can be overridden
