replicaCount: 2

image:
  repository: nitzanm594/weatherapp-tsg
  tag: "63" 
  pullPolicy: Always
imagePullSecrets:
  - name: dockerhub
# service:
#   type: NodePort
#   port:  9090
#   targetPort: 9090
#   nodePort: 30000
service:
  enabled: true
  type: ClusterIP
  port: 80
  targetPort: 9090

# ingress:
#   enabled: false
#   annotations: {}
#   hosts:
#     - host: my-python-app.local
#       paths:
#         - path: /
#           pathType: ImplementationSpecific

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

config:
  bgColor: "blue"  # Default blue, can be overridden
