apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-app-config
  annotations:
    checksum/values: {{ toYaml .Values.config | sha256sum }}
data:
  BG_COLOR: {{ .Values.config.bgColor  }}
